# Site settings
title: "My Jekyll Resume"
description: "My resume for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Anh-Duc Nguyen"
resume_title:                   "A Machine Teacher"
resume_contact_email:           "adnguyen@yonsei.ac.kr"
resume_contact_telephone:       "+82-10-3458-9210"
resume_contact_address:         "Donggyo-ro 296-38, Seodaemun-gu, Seoul, 037-16"
resume_header_contact_info: "Donggyo-ro 296-38, Seodaemun-gu, Seoul, 037-16 | +8210-3458-9210 | adnguyen@yonsei.ac.kr"
resume_header_intro: "<p>I am a passionate human trying to teach machine to learn. Currently, I am working towards my PhD in Computer Vision at Yonsei University. I am interested in computer vision, machine learning, deep learning, and statistics.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
#resume_section_experience:      true
resume_section_education:       true
resume_section_publications:    true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
#resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/justanhduc"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://m.facebook.com/Mr.DucAnhNguyen"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://adnlearningblog.wordpress.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
